version: '3.8'

services:
  portfolio_web:
    build: .
    container_name: yerniyaz_portfolio
    restart: unless-stopped
    ports:
      - "8085:80" # Порт 8080 на сервере смотрит на 80 в контейнере