server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Включаем Gzip-сжатие (сайт будет весить в 3 раза меньше при загрузке)
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml application/javascript image/svg+xml;
    gzip_disable "MSIE [1-6]\.";

    # Основной роутинг для React SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Кэширование статики на 6 месяцев (шрифты, картинки, CSS, JS)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|jpg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}